services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    environment:
      POSTGRES_PASSWORD: test123
    ports:
      - "5433:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: >
        pg_isready -U postgres -d postgres
        && psql -U postgres -d postgres -tA \
             -c "SELECT 1 FROM pg_tables WHERE tablename = 'preguntas_frecuentes';"
      interval: 5s
      timeout: 5s
      retries: 5

  dulcebot:
    build: .
    container_name: dulcebot
    depends_on:
      pgvector:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    # ← aquí corriges el comando de Chainlit:
    command: ["sh","-c","python vectorizar.py && chainlit run --host 0.0.0.0 --port 8000 dulcebot.py"]

volumes:
  pgvector-data:
